services:
  - type: web
    name: framekeeper-site
    runtime: static
    rootDir: streamer-site
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
